# Generated by Django 4.0.3 on 2022-04-01 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0004_profile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product_name', models.CharField(max_length=45)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=45)),
                ('product_description', models.TextField(max_length=250)),
                ('product_photo', models.ImageField(upload_to='product_photos/')),
                ('product_quantity', models.IntegerField()),
                ('product_type', models.CharField(choices=[('PAINTING', 'Painting'), ('PRINT', 'Print'), ('PIN', 'Pin'), ('STICKERS', 'Stickers'), ('DOLL', 'Doll'), ('CLOTHING', 'Clothing'), ('OTHER', 'Other')], max_length=8)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile')),
            ],
        ),
    ]
