# Generated by Django 4.0.3 on 2022-03-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
