# Generated by Django 4.0.3 on 2022-03-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=12.12, max_digits=7),
            preserve_default=False,
        ),
    ]
