# Generated by Django 4.0.3 on 2022-04-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cartitem_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
