# Generated by Django 4.0.3 on 2022-04-07 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='crated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
