# Generated by Django 4.0.3 on 2022-03-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_address_primary_alter_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default=1, upload_to='profile_photos/'),
            preserve_default=False,
        ),
    ]
