# Generated by Django 4.0.3 on 2022-04-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
