# Generated by Django 4.0.3 on 2022-04-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_rename_based_in_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
