# Generated by Django 4.0.3 on 2022-04-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0011_profile_shop_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shop_banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner_photos/'),
        ),
    ]
