# Generated by Django 4.0.3 on 2022-04-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0012_alter_profile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default=1, upload_to='profile_photos/'),
            preserve_default=False,
        ),
    ]
